### ISSUE TITLE
Lights - Blinking Signals

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Embedded-Software#41]
The lights board should have the right and left signals blink. Currently they are just ON when toggled.

**Comment by enochtsang** [comment]
Are you sure about this? I very specifically checked this after I finished it.

**Comment by bill-luu** [comment]
Sorry I think you're right (I'll triple check though) I think that I meant to say that the BMS strobe light needs to actually strobe. I will update the issue
