### ISSUE TITLE
CCS - Verify BatteryFault Serial Sending

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Embedded-Software#42]
So the batteryfaults data in the protocol was updated: The limit flags should have been put into index 4 of the payload instead of 5 (That was the cause of the test tool issue we've been having since the summer). 

Check if CCS has that error as well, and if so fix it.

**Comment by Reddragoneer1** [comment]
https://github.com/UCSolarCarTeam/Epsilon-Embedded-Software/blob/master/EpsilonCCS/Src/TelemetryReporting/TelemetryReporting.c
Line 204 has index 5 instead of 4, and needs to be switched
