### ISSUE TITLE
Set Current Derivation

### ISSUE THREAD

**Issue by bill-luu** [UCSolarCarTeam/Epsilon-Embedded-Software#66]
CCS currently has fields for the setCurrent & setVelocity fields. However they are never being set, where are they supposed to come from?

**Comment by enochtsang** [comment]
Those are from driver controls. It's the current and velocity we set from the driver controls.

**Comment by bill-luu** [comment]
Between CAN & Serial, the Set Current is reported as a percentage. In internet reporting, the value is supposed to be in amps, how is this conversion done?

**Comment by enochtsang** [comment]
I think it should always be in amps, I'm not actually sure of this atm, you should set it to what you see fit. It's basically a way to report driver input, don't worry too much about getting it right according to something, it's completley something we created.
